### PR TITLE
Add the Chinese version of index page

### PR DESCRIPTION
**Pull request by nevermosby**
This PR is to add Chinese version of index page so that bumblebee.io can support multi-language.
You can find the preview below:

Any suggestions are welcome.

### CODE REVIEW

**Comment by linsun** [comment]
LGTM, thank you @nevermosby!

How does user get to this page or is it automatically loaded when Chinese is the preferred language?

cc @Worfle

**Comment by Worfle** [comment]
@nevermosby Thanks so much!  I just started on a way to integrate other languages in a slightly different way. 

My goal was to just add a languages file with some Typescript-enforced json objects which we then just read in to overwrite the language parts of the main content file. (Think something like:
   `{ 
       EN: { 
         headerContent: "BumbleBee simplifies...", ...
       },  
       ZH: { 
         headerContent: "BumbleBee简化了eBPF工具的构建过程，并...", ... 
       } 
     } 
 `
 
 Do you think this would be an issue?  My knowledge of Chinese sites is that this wouldn't cause any issues with styling, etc.  (and I can do a bit more work for right-to-left languages like Hebrew in the future) 
 
 
 EDIT :: I'll have that upgrade in within the next hour if it would help to read the details first.

**Comment by Worfle** [comment]
@nevermosby  I've pushed my change directly.  Give it a look in the `languages.ts` file. You should be able to just:
   1 - Fill in the 'Placeholder' values with what you've already written up.
   2 - Run `yarn start` to start local as normal
   3 - Go to the bottom of the site and toggle between the 'English' and '中文' to see content change.

**Comment by nevermosby** [comment]
Hi @Worfle, I will take a look and update my work soon.

**Comment by nevermosby** [comment]
@Worfle I have done the update. Pls help review :)

**Review by linsun — APPROVED** [review]

**Comment by linsun** [comment]
@Worfle pinged me and said `LGTM`.  

The translation LGTM as well.

Thank you @nevermosby for your contribution!!

**Pull request merged**
